#!/usr/bin/env ruby
#
# Script that you can alias as ls, and it will integrate with "svn st" to
# include SVN status information in the directory listing.
# Includes terminal colours for the different statuses.
# Project: http://github.com/jstirk/jstirk-admin-helper-scripts/
# Author: Jason Stirk (http://griffin.oobleyboo.com)
# Date: 29Sep2008

# Personally, I add the following to my .bashrc so as that this is always used
# alias ls='~/bin/rsls'

###############################################################
cmd="ls --color=always #{ARGV.join(' ')}"
lsinfo=`#{cmd}`

# Strip out the args so as that we just have the path
path=cmd.gsub(/ls| -[\-A-Z0-9\=]+( [A-Z0-9]+)?/i, '').strip
if path == '' then
  svn_path='.svn'
else
  # Otherwise, we will get "/.svn" which is wrong
  svn_path=File.join(path, '.svn')
end

files={}
if File.exist?(svn_path) then
  cmd='svn st'
  # Only cd if it's in a different path to where we are now
  cmd="cd #{path}; #{cmd}" unless path == ''

  `#{cmd}`.split(/\r\n|\r|\n/).each do |line|
    ms=line.strip.match(/^\s*([^\s]+)[\s \+]+(.*)(\/.*)?$/i)
    if ms[2] =~ /\// then
      # Has a slash, so show a property on the directory
      ma=ms[2].gsub(/([^\/]+)\/.*$/, '\1')
      mt=ms[1]
    else
      ma=ms[2]
      mt=ms[1]
    end
    case ms[1]
      when /A/i
        cc="\e[01;32m"
      when /D/i, /!/i, /C/i
        cc="\e[01;31m"
      when /M/i
        cc="\e[01;36m"
      when '?'
        cc="\e[01;33m"
    end
    if ma != '.' then
      files[ma] ||= ''
      files[ma] << "#{cc}#{mt}"
    end
  end
end
reset="\e[00;00m"
files.each do |f,v|
  v=v.gsub(/([ADMC!\?\*].*)/, '(\1)')
  lsinfo.gsub!(/(#{f})([^.])/, "\\1#{v}#{reset}\\2")
end
print lsinfo
